---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
  - name: centos-7.1

suites:
  - name: scheduler
    run_list:
      - recipe[apt]
      - recipe[aurora::scheduler]
    attributes:
      aurora:
        scheduler:
          autoinit_db: true

  - name: slave
    run_list:
      - recipe[apt]
      - recipe[aurora::slave]

  - name: client
    run_list:
      - recipe[apt]
      - recipe[aurora::client]
